version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: reaganenoch
      POSTGRES_DB: echo_psychology
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://reaganenoch@db:5432/echo_psychology?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    command: ["/bin/sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run dev"]

volumes:
  postgres_data:
